// Open a new window with styled HTML and trigger the browser's Save-as-PDF / Print dialog.
// Works without any dependency.

function openPrintable(title, bodyHTML) {
  const w = window.open("", "_blank", "width=820,height=900");
  if (!w) {
    // Popup blocked — fall back to in-page modal? For now just log.
    alert("Please allow pop-ups to download the document.");
    return null;
  }
  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<title>${title}</title>
<style>
  :root { --ink: #1F2420; --muted: #5B645C; --rule: #E8E2D3; --paper: #F6F3EC; --accent: #B77742; }
  * { box-sizing: border-box; }
  body { font-family: 'Inter', system-ui, sans-serif; color: var(--ink); padding: 48px; max-width: 760px; margin: 0 auto; background: white; line-height: 1.5; }
  h1, h2, h3 { font-family: 'Fraunces', Georgia, serif; letter-spacing: -0.01em; margin: 0 0 12px; }
  h1 { font-size: 36px; line-height: 1.05; }
  h2 { font-size: 22px; margin-top: 32px; }
  h3 { font-size: 16px; }
  .brand { display: flex; align-items: center; gap: 10px; color: var(--ink); }
  .brand-mark { width: 36px; height: 36px; border-radius: 12px; background: var(--accent); color: white; display: flex; align-items: center; justify-content: center; font-family: 'Fraunces', serif; font-weight: 600; }
  .muted { color: var(--muted); }
  .eyebrow { font-family: 'JetBrains Mono', ui-monospace, monospace; font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase; color: var(--muted); }
  .rule { height: 1px; background: var(--rule); margin: 24px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  td { padding: 10px 12px; border-bottom: 1px solid var(--rule); font-size: 14px; vertical-align: top; }
  td:first-child { color: var(--muted); width: 35%; }
  .stamp { display: inline-block; padding: 8px 14px; border: 2px solid var(--accent); color: var(--accent); border-radius: 999px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; font-size: 12px; }
  .sig { margin-top: 48px; display: grid; grid-template-columns: 1fr 1fr; gap: 32px; }
  .sig .line { border-top: 1px solid var(--ink); padding-top: 8px; font-size: 12px; color: var(--muted); }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--rule); font-size: 11px; color: var(--muted); text-align: center; }
  @media print {
    body { padding: 24px; }
    .noprint { display: none; }
  }
  .actions { position: fixed; top: 16px; right: 16px; display: flex; gap: 8px; }
  .btn { border: 1px solid var(--rule); background: white; color: var(--ink); padding: 8px 14px; border-radius: 999px; font-size: 13px; cursor: pointer; }
  .btn.primary { background: var(--ink); color: white; border-color: var(--ink); }
</style>
</head>
<body>
  <div class="noprint actions">
    <button class="btn" onclick="window.close()">Close</button>
    <button class="btn primary" onclick="window.print()">Print / Save as PDF</button>
  </div>
  ${bodyHTML}
  <div class="footer">Generated by Rentora &middot; Indore &middot; ${new Date().toLocaleString("en-IN")}</div>
</body>
</html>`;
  w.document.open();
  w.document.write(html);
  w.document.close();
  // Give the DOM a tick, then auto-open print dialog (user can cancel).
  setTimeout(() => { try { w.focus(); w.print(); } catch (e) { /* ignore */ } }, 400);
  return w;
}

function fmtINR(n) { return "₹" + (Number(n) || 0).toLocaleString("en-IN"); }
function fmtDate(d) { return d ? new Date(d).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) : "—"; }

export function generateAgreementPDF({ booking, property, owner, tenant }) {
  const rent = booking?.priceQuoted || property?.price || 0;
  const deposit = rent * 2;
  const body = `
    <header class="brand"><div class="brand-mark">R</div><div><div style="font-weight:600;font-size:18px;">Rentora</div><div class="eyebrow">Rental Agreement</div></div></header>
    <div class="rule"></div>

    <h1>Rental Agreement</h1>
    <p class="muted">This agreement is made between the Owner and the Tenant for the property listed below. It is governed by the laws of India and the state of Madhya Pradesh.</p>

    <h2>Parties</h2>
    <table>
      <tr><td>Owner</td><td><b>${owner?.name || owner?.ownerKYC?.ownerName || "—"}</b><br/><span class="muted">${owner?.email || "—"}${owner?.ownerKYC?.ownerPhone ? " · " + owner.ownerKYC.ownerPhone : ""}</span></td></tr>
      <tr><td>Tenant</td><td><b>${tenant?.name || "—"}</b><br/><span class="muted">${tenant?.email || "—"}</span></td></tr>
    </table>

    <h2>Property</h2>
    <table>
      <tr><td>Name</td><td>${property?.title || "—"}</td></tr>
      <tr><td>Address</td><td>${property?.location?.address || ""}${property?.location?.locality ? ", " + property.location.locality : ""}${property?.location?.city ? ", " + property.location.city : ""}${property?.location?.pincode ? " – " + property.location.pincode : ""}</td></tr>
      ${property?.bedrooms != null ? `<tr><td>Configuration</td><td>${property.bedrooms} BHK</td></tr>` : ""}
      ${property?.furnishing ? `<tr><td>Furnishing</td><td>${property.furnishing}</td></tr>` : ""}
    </table>

    <h2>Tenancy Terms</h2>
    <table>
      <tr><td>Move-in date</td><td>${fmtDate(booking?.checkIn)}</td></tr>
      <tr><td>Lease end</td><td>${fmtDate(booking?.checkOut)}</td></tr>
      <tr><td>Monthly rent</td><td>${fmtINR(rent)}</td></tr>
      <tr><td>Security deposit</td><td>${fmtINR(deposit)}<span class="muted"> (refundable on move-out, subject to deductions)</span></td></tr>
      <tr><td>Brokerage</td><td><b style="color:#2d7a4a">₹0 — always</b></td></tr>
      <tr><td>Notice period</td><td>1 month</td></tr>
    </table>

    <h2>Standard Clauses</h2>
    <ol class="muted" style="padding-left: 20px; line-height: 1.7;">
      <li>The Tenant shall pay the monthly rent on or before the 5th of each calendar month via Rentora&rsquo;s online portal.</li>
      <li>The deposit shall be refunded within 15 days of vacating, after deducting damages (if any) and unpaid dues.</li>
      <li>The Tenant shall keep the premises in a reasonable state of cleanliness and promptly report any maintenance issues via the Raise Issue flow on Rentora.</li>
      <li>The Tenant shall not sublet or share the premises without written consent of the Owner.</li>
      <li>The Owner shall provide a minimum of 24 hours&rsquo; notice before entering the premises for inspection.</li>
      <li>This agreement may be terminated by either party with a 1-month written notice.</li>
      <li>Any dispute shall first be mediated by Rentora&rsquo;s support team before escalation.</li>
    </ol>

    <div class="rule"></div>
    <div style="display:flex;justify-content:space-between;align-items:center;gap:16px;">
      <div class="stamp">Digitally agreed</div>
      <div class="muted" style="font-size:12px;">Agreement ID: RA-${String(booking?._id || "").slice(-8).toUpperCase()} &middot; Generated ${fmtDate(new Date())}</div>
    </div>

    <div class="sig">
      <div><div class="line">Tenant signature &middot; ${tenant?.name || "—"}</div></div>
      <div><div class="line">Owner signature &middot; ${owner?.name || owner?.ownerKYC?.ownerName || "—"}</div></div>
    </div>
  `;
  return openPrintable(`Rental Agreement — ${property?.title || "Rentora"}`, body);
}

export function generateReceiptPDF(payment) {
  const body = `
    <header class="brand"><div class="brand-mark">R</div><div><div style="font-weight:600;font-size:18px;">Rentora</div><div class="eyebrow">Rent Receipt</div></div></header>
    <div class="rule"></div>

    <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:24px;">
      <div>
        <h1>Rent Receipt</h1>
        <p class="muted">Receipt number <b style="color:var(--ink);font-family:'JetBrains Mono',monospace;">${payment.receiptNumber}</b></p>
      </div>
      <div class="stamp">Paid</div>
    </div>

    <h2>Details</h2>
    <table>
      <tr><td>Property</td><td>${payment.property?.title || "—"}</td></tr>
      <tr><td>Tenant</td><td>${payment.tenant?.name || "—"}<br/><span class="muted">${payment.tenant?.email || ""}</span></td></tr>
      <tr><td>Owner</td><td>${payment.owner?.name || "—"}<br/><span class="muted">${payment.owner?.email || ""}</span></td></tr>
      <tr><td>Period</td><td><b>${payment.periodLabel}</b></td></tr>
      <tr><td>Method</td><td>${payment.method}</td></tr>
      <tr><td>Paid on</td><td>${fmtDate(payment.paidAt)}</td></tr>
      <tr><td>Amount</td><td><b style="font-size:18px;">${fmtINR(payment.amount)}</b></td></tr>
    </table>

    <div class="rule"></div>
    <p class="muted" style="font-size:12px;">This receipt is computer-generated and valid without signature. For queries, write to hello@rentora.in with the receipt number.</p>
  `;
  return openPrintable(`Receipt — ${payment.receiptNumber}`, body);
}
